# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 731e0b1f8f44529f9f24ab244c9a368917b6bf416795e7baa95bdb91c13390e0740a346c5e46c6ec17d6a357b6f99b24b43ea6b940b4625a25faabbccab390a0

test:
  secret_key_base: 37bc71b1e986c937d6fbce6d2237c4f614d661649bcd46014d999e2420453cfdd81be98520cfd71d861b7d3709f2ef5883abf4352bc2d89d4afa59d7732e9f22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
