max_lenght_name: 50
max_lenght_email: 255
min_lenght_pass: 6
max_picture_size: 5
avatar_size_partial: 30
picture_size: 80
picture_size_index: 50
item_per_page: 10
checkbox_true: 1
time_mail_expire: 2
mail_default: "noreply@example.com"
post_lenght: 140
micropost_label: "micropost"
picture_dism_limit: 400
